<?php
// $Id: date_tools.module,v 1.13 2010/04/13 19:35:33 karens Exp $

/**
 * Implementation of hook_help().
 */
function date_tools_help($section, $arg) {
  switch ($section) {
    case 'admin/structure/date':
      return '<p>' . t('Tools for creating and importing dates and calendars.') . '</p>';

    case 'admin/structure/date/change':
      return '<p>'. t('Change a date field from one type to another. Very experimental, use at your own risk!') .'</p>';
                 
    case 'admin/structure/date/date_wizard':
      $disabled_modules = date_tools_wizard_disabled_modules(array('popup', 'repeat', 'linked'));
      if (!empty($disabled_modules)) {
        drupal_set_message(t('The following modules are required for the wizard to work:') . '<ul><li>' . implode('</li><li>', $disabled_modules) . '</li></ul>', 'error');
      }
      $output =        
      t('Fill out the following form to auto-create a date content type, with a datetime field and matching pre-configured calendar. A calendar and upcoming events block will be created, an ical feed will be added to the calendar, and the mini calendar, calendar legend, and upcoming events blocks will be added to the sidebar of the default theme. Nodes created from this new content type will include a link to the calendar, and the calendar will have a link to the \'add new date\' form. You can also add new date fields to an existing content type by entering the existing content type name instead of creating a new one.') .
      '</p><p>' .
      t('Only a limited set of options are displayed here to make this easy to set up. Once the date has been created you will be able to make other changes to the date settings and add other fields to your new content type on the Manage fields screen, and make changes to the calendar on the Views edit page.') .
      '</p>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function date_tools_permission() {
  return array('administer date tools');
}

/**
 * Implements hook_menu().
 */
function date_tools_menu() {

  $items = array();
  $items['admin/structure/date'] = array(
    'title'    => 'Date Tools',
    'description' => 'Tools to import and auto-create dates and calendars. ',
    'access arguments'   => array('administer date tools'),
    'page callback' => 'date_tools_page',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/date/about'] = array(
    'title' => 'About',
    'description' => 'Tools to import and auto-create dates and calendars. ',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -5,
    'page callback' => 'date_tools_page',
    'access arguments' => array('administer date tools'),
  );
  $items['admin/structure/date/date_wizard'] = array(
    'title' => 'Date wizard',
    'description' => 'Easy creation of date content types and calendars. ',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('date_tools_wizard_form'),
    'access arguments' => array('administer date tools'),
    'file' => 'date_tools.wizard.inc',  
  );
  $items['admin/structure/date/remove'] = array(
    'title'    => 'Remove calendar',
    'access arguments'   => array('administer date tools'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('date_tools_remove_form', 3),
    'type' => MENU_CALLBACK,
  );
  $items['admin/structure/date/change'] = array(
    'title'    => 'Change',
    'access arguments'   => array('administer date tools'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('date_tools_change_type_form'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 3,
    'file' => 'date_tools.change_type.inc',
    'path' => drupal_get_path('module', 'date_tools'),
  );
  return $items;
}

/**
 *  Main Date Tools page
 */
function date_tools_page() {
  $choices = array();
  $choices[] = t('Dates and calendars can be complicated to set up. The !date_wizard makes it easy to create a simple date content type and related calendar. ', array('!date_wizard' => l(t('Date wizard'), 'admin/structure/date/date_wizard')));
  $content = '<ul><li>' . implode('</li><li>', $choices) . '</li></ul>';

  if (module_exists('calendar')) {
    $calendar_options = variable_get('calendar_default_view_options', array());
    $calendars = array();
    $node_types = node_get_types();
    foreach ($calendar_options as $key => $option) {
      $bundle = str_replace('calendar_', '', $key);
      if (array_key_exists($bundle, $node_types)) {
        $type = $node_types[$bundle];
        $calendars[] = array(
          l($type->name, 'admin/structure/types/manage/' . $bundle . '/fields'), 
          l($key, 'admin/structure/views/edit/' . $key), 
          t('The calendar %view is a default calendar created for the content type %bundle. ', array('%view' => $key, '%bundle' => $type->name)),
          l(t('remove !view', array('!view' => $key)), 'admin/structure/date/remove/' . $key),
        );
      }
      else {
        // Do some cleanup while we're here if we have default calendars
        // for non-existent content types.
        calendar_remove($bundle);
      }
    }
    if (!empty($calendars)) {
      $headers = array(t('Content Type'), t('Calendar'), t('Description'), t('Operations'));
      $content .= theme('table', $headers, $calendars);
    }
  }
  
  return $content;
}

/**
 * Menu callback; present a form for removing a field from a content type.
 */
function date_tools_remove_form(&$form_state, $view_name) {
  $form = array();
  $form['view_name'] = array(
    '#type' => 'value',
    '#value' => $view_name,
  );
  $output = confirm_form($form,
    t('Are you sure you want to remove the view %view?', array('%view' => $view_name)),
    'admin/structure/date',
    t('This action cannot be undone.'),
    t('Remove'), t('Cancel')
  );

  return $output;
}

/**
 * Remove a field from a content type.
 */
function date_tools_remove_form_submit($form, &$form_state) {
  $form_values = $form_state['values'];
  $view_name = $form_values['view_name'];
  
  if ($view_name && $form_values['confirm']) {
    calendar_remove($view_name);
    drupal_set_message(t('Removed calendar %calendar. ', array(
      '%calendar' => $view_name)));
  }
  $form_state['redirect'] = 'admin/structure/date';
}

/**
 * Helper function to create a field array with default values for a date 
 * $field, based on field type, widget type, and timezone handling.
 * 
 * This function can be used to make it easier to create new date fields
 * in profiles or custom code.
 * 
 * @param $field_type
 *   Can be 'date', 'datestamp', or 'datetime' .
 * @param $widget_type
 *   Can be 'date_text', 'date_text_repeat', 'date_select', 
 *   'date_select_repeat', 'date_popup', 'date_popup_repeat' .
 * @param $tz_handling
 *   Can be 'site', 'date', 'utc', 'none', or 'user' .
 * @param $overrides
 *   An optional array of field/widget values that should 
 *   override the normal defaults.
 */
function date_tools_default_values($field_type, $widget_type, $tz_handling, $overrides = array()) {
  module_load_include('inc', 'field', 'field.crud');
  $repeat_widgets = array('date_select_repeat', 'date_text_repeat', 'date_popup_repeat');
  
  $base_field_values = array(
    'settings' => array(
      'timezone_db' => date_get_timezone_db($tz_handling),
      'tz_handling' => $tz_handling,
      'todate' => 'optional',
      'repeat' => in_array($widget_type, $repeat_widgets) ? 1 : 0,
      'default_format' => 'medium',
    ),
  );
  $base_instance_values = array(
    'widget' => array(
      'settings' => array(
        'input_format' => date_default_format($widget_type),
        'increment' => 15,
      ),
    ),
  );
  $field_values['date'] = $base_field_values;
  $field_values['date']['type'] = 'date';
  
  $field_values['datestamp'] = $base_field_values;
  $field_values['datestamp']['widget']['type'] = 'datestamp';

  $field_values['datetime'] = $base_field_values;
  $field_values['datetime']['widget']['type'] = 'datetime';

  $instance_values['date_select'] = $base_instance_values;
  $instance_values['date_select']['widget']['type'] = 'date_select';
  
  $instance_values['date_text'] = $base_instance_values;
  $instance_values['date_text']['widget']['type'] = 'date_text';
  
  $instance_values['date_popup'] = $base_instance_values;
  $instance_values['date_popup']['widget']['type'] = 'date_popup';
    
  $instance_values['date_select_repeat'] = $base_instance_values;
  $instance_values['date_select_repeat']['widget']['type'] = 'date_select_repeat';
  
  $instance_values['date_text_repeat'] = $base_instance_values;
  $instance_values['date_text_repeat']['widget']['type'] = 'date_text_repeat';
  
  $instance_values['date_popup_repeat'] = $base_instance_values;
  $instance_values['date_popup_repeat']['widget']['type'] = 'date_popup_repeat';
  
  // Get the basic field array with field module default values.
  $field = array('field_name' => '', 'type' => '');
  $instance = array('field_name' => '', 'entity_type' => 'node', 'bundle' => '');

  // Update it with default values for this date field and widget type.
  _date_tools_overrides(&$field, $field_values[$field_type]);
  _date_tools_overrides(&$instance, $instance_values[$widget_type]);
  
  // Allow overrides of specific default values. 
  _date_tools_overrides(&$field, $overrides['field']);
  _date_tools_overrides(&$instance, $overrides['instance']);

  // Make sure multiple gets set correctly for repeating dates.
  if ($field['settings']['repeat']) $field['cardinality'] = FIELD_CARDINALITY_UNLIMITED;
  
  return array('field' => $field, 'instance' => $instance);
}

/**
 * Helper function to update field and instance values.
 */
function _date_tools_overrides(&$base, $values) {
  foreach ($values as $key => $value) {
    if (is_array($value)) {
      foreach ($value as $key2 => $value2) {
        if (is_array($value2)) {
          foreach ($value2 as $key3 => $value3) {
            $base[$key][$key2][$key3] = $value3;
          }
        }
        else {
          $base[$key][$key2] = $value2;
        }
      }
    }
    else {
      $base[$key] = $value;
    }  
  } 
}