<?php
// $Id: plus1.module,v 1.1.4.8 2009/03/18 05:04:42 chill35 Exp $
 /**
 * @file
 * A simple +1 voting widget module.
 */

/**
* Implements of hook_perm().
*/
function plus1_permission() {
  return array(
    'vote on content' =>  array(
      'title' => 'Vote on content',
      'description' => 'Cast votes on site content using the Plus1 voting widget.',
    ),
    'administer the voting widget' =>  array(
      'title' => 'Administer the voting widget',
      'description' => 'Make configuration changes to the Plus1 voting widget.',
    ),
  );
}

/**
* Implements of hook_menu().
*/
function plus1_menu() {

  $items['plus1/vote/%'] = array(
    'title' => 'Vote',
    'page callback' => 'plus1_vote',
    'page arguments' => array(2),
    'access arguments' => array('vote on content'),
    'type' => MENU_CALLBACK,
  );

  $items['admin/structure/plus1'] = array(
    'title' => 'Plus 1',
    'description' => 'Allows readers to vote on content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('plus1_settings'),
    'access arguments' => array('administer the voting widget'),
  );

  return $items;
}

/**
* Implements of hook_init().
*/
function plus1_init() {
  variable_set('plus1_javascript_settings', 0);
}

/**
* Menu callback to configure module settings.
*/
function plus1_settings() {

  $form['plus1_nodetypes_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Content type settings'),
    '#description' => t('Select all node types to which a +1 voting widget can be added.'),
  );

  $form['plus1_nodetypes_fieldset']['plus1_nodetypes'] = array(
    '#type' => 'checkboxes',
    '#options' => node_type_get_names(),
    '#default_value' => variable_get('plus1_nodetypes', array('story')),
  );

  $form['plus1_display'] = array(
    '#type' => 'fieldset',
    '#title' => t('Display settings'),
    '#description' => t('You may select none, one or both options.'),
  );

  $form['plus1_display']['plus1_in_teaser'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a +1 voting widget to the node in teaser view.'),
    '#default_value' => variable_get('plus1_in_teaser', 0),
  );

  $form['plus1_display']['plus1_in_full_view'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a +1 voting widget to the node in full view.'),
    '#default_value' => variable_get('plus1_in_full_view', 1),
  );

    $form['plus1_display']['plus1_in_full_view'] = array(
    '#type' => 'checkbox',
    '#title' => t('Add a +1 voting widget to the node in full view.'),
    '#default_value' => variable_get('plus1_in_full_view', 1),
  );

  $form['plus1_text'] = array(
    '#type' => 'fieldset',
    '#title' => t('Text settings'),
  );

  $form['plus1_text']['plus1_you_voted'] = array(
    '#type' => 'textfield',
    '#title' => t('Feedback provided to voter when he already voted'),
    '#default_value' => variable_get('plus1_you_voted', t('You voted')),
    '#description' => t('Enter, for example, <em>Dugg</em>, <em>You voted</em>, or <em>Voted</em>.'),
  );
  
  $form['plus1_weight'] = array(
    '#type' => 'fieldset',
    '#title' => t('Weight settings'),
  );

  $form['plus1_weight']['plus1_weight'] = array(
    '#type' => 'textfield',
    '#title' => t('Weight of voting widget'),
    '#default_value' => variable_get('plus1_weight', '100'),
    '#description' => t('The higher the weight the lower in the node the widget will be added. Can be a negative number.'),
  );

  $form['array_filter'] = array('#type' => 'hidden');

  return system_settings_form($form);
}

/**
* Page callback.
* @param $nid
* A node ID.
* @param $ajax
* Equal to 'json' when the function is called by jQuery.
* Submits the vote request and refreshes the page without JavaScript.
* Otherwise, it submits the vote request and returns JSON to be parsed by jQuery.
*/
function plus1_vote($nid) {
  global $user;
  $json = isset($_GET['json']) ? 'json' : NULL;
  if (!drupal_valid_token($_GET['token'], $nid)) {
    watchdog('Plus1', 'Voting form error: Invalid token.');
    return drupal_access_denied();
  }

  $voted = plus1_get_votes($nid, $user->uid);
  // If the voter has not already voted.
  if (!$voted) {
    $node_type = db_select('node','n')->fields('n', array('type'))->condition('nid', $nid)->execute()->fetchObject();
    $votes[] = array(
      'entity_id' => $nid,
      'entity_type' => $node_type->type,
      'value_type' => 'points',
      'value' => 1,
    );
    votingapi_set_votes($votes);
    $criteria = array(
      'entity_id' => $nid,
      'function' => 'sum',
    );
    $results = votingapi_select_results($criteria);
    if ($json == 'json') {
      // This print statement will return results to jQuery's request.
       drupal_json_output(array('score' => $results[0]['value'], 'voted' => check_plain(variable_get('plus1_you_voted', t('You voted')))));
    }
    else {
      // Go to the full node view.
      drupal_set_message(t('Thank you for your vote.'));
      drupal_goto('node/' . $nid);
    }
  }
}

/**
* Return the number of votes for a given node ID/user ID pair.
*
* @param $nid
* A node ID.
* @param $uid
* A user ID.
* @return Integer
* Number of votes the user has cast on this node.
*/
function plus1_get_votes($nid, $uid) {
  $criteria['entity_id'] = $nid;
  $criteria['value_type'] = 'points';
  if ($uid == 0) {
    $criteria['vote_source'] = ip_address();
  }
  else {
    $criteria['uid'] = $uid;
  }
  $results = votingapi_select_votes($criteria);
  return count($results);
}

/**
* Return the total score of a node.
*
* @param $nid
* A node ID.
* @return Integer
* The score.
*/
function plus1_get_score($nid) {
  $criteria['entity_id'] = $nid;
  $criteria['value_type'] = 'points';
  $criteria['function'] = 'sum';
  $results = votingapi_select_results($criteria);
  if (empty($results)) {
    return 0;
  }
  else {
    return $results[0]['value'];
  }
}

/**
* Create voting widget to display on the webpage.
*/
function plus1_jquery_widget($node, $teaser) {
  $score = plus1_get_score($node->nid);
  global $user;
  // If user is not logged-in.
  if ($user->uid == 0) {
    $logged_in = FALSE;
    $is_author = FALSE;
  }
  else {
    $logged_in = TRUE;
    $is_author = ($node->uid == $user->uid)? TRUE : FALSE;
  }
  $voted = plus1_get_votes($node->nid, $user->uid);
  return theme('plus1_widget', array('node' => $node, 'score' => $score, 'logged_in' => $logged_in, 'is_author' => $is_author, 'voted' => $voted, 'teaser' => $teaser));
  
}

/**
* Implements of hook_nodeapi().
*/
function plus1_node_view($node, $buildmode, $langcode) {
       if (in_array($node->type, variable_get('plus1_nodetypes', array('story')))) {
           $teaser = variable_get('plus1_in_teaser', 0);
           $full  = variable_get('plus1_in_full_view', 1);
           if (($buildmode == 'full' && $full) || ($buildmode='teaser' && $teaser)) {
               $node->content['plus1_widget'] = array(
                                '#markup' => plus1_jquery_widget($node, ($buildmode == 'teaser'), FALSE),
                                '#weight' => (int) variable_get('plus1_weight', '100'),
                                );
          }
 
  }
}

function plus1_node_delete($node){
 var_dump($node);
 exit();
}

/**
* Implements of hook_theme().
*/
function plus1_theme() {
    $theme['plus1_widget'] = array(
        'arguments' => array('node', 'score', 'logged_in', 'is_author', 'voted', 'teaser', 'page'),
        'template' => 'plus1-widget',
    );
    return $theme;
}

/**
* Theme for the voting widget.
*
* You are free to load your own CSS and JavaScript files in your
* theming function override, instead of the ones provided by default.
*
* This function adds information to the Drupal.settings.plus1 JS object,
* concerning class names used for the voting widget.
* If you override this theming function but choose to use the
* default JavaScript file, simply assign different values to
* the following variables:
*    $widget_class   (The wrapper element for the voting widget.)
*    $link_class     (The anchor element to cast a vote.)
*    $message_class  (The wrapper element for the anchor element. May contain feedback when the vote has been cast.)
*    $score_class    (The placeholder element for the score.)
* The JavaScript looks for these CSS hooks to
* update the voting widget after a vote is cast.
* Of course you may choose to write your own JavaScript.
* The JavaScript adds presentation, ie: fade in.
*
*/
function template_preprocess_plus1_widget(&$variables) {
   extract($variables);
  // Load the JavaScript and CSS files.
  // You are free to load your own JavaScript files in your theming function to override.
  drupal_add_js(drupal_get_path('module', 'plus1') . '/jquery.plus1.js');
  drupal_add_css(drupal_get_path('module', 'plus1') . '/plus1.css');

  
  
  $variables['plus1']['widget_class']  = 'plus1-widget';
  $variables['plus1']['link_class']    = 'plus1-link';
  $variables['plus1']['message_class'] = 'plus1-msg';
  $variables['plus1']['score_class']   = 'plus1-score';
  $variables['plus1']['loginvote']     = l(t('Log in<br />to vote'), 'user', array('html' => TRUE));
  $variables['plus1']['youvoted']      = check_plain(variable_get('plus1_you_voted', t('You voted')));
  $variables['plus1']['linkvote']      = l(t('Vote'), 'plus1/vote/' . $node->nid, array('query' =>
                                                                      array('token' => drupal_get_token($node->nid)), 'attributes' => array('class' => $variables['plus1']['link_class'])));

  // Attaching these hooks names to the Drupal.settings.plus1 JavaScript object.
  // So these class names are NOT hard-coded in the JavaScript.
  if (variable_get('plus1_javascript_settings', 0) == 0) {
    drupal_add_js(array('plus1' => array('widget_class' =>   $variables['plus1']['widget_class'], 'link_class' =>  $variables['plus1']['link_class'] ,
                                                                                                  'message_class' => $variables['plus1']['message_class'],
                                                                                                  'score_class' => $variables['plus1']['score_class'])), 'setting');
    variable_set('plus1_javascript_settings', 1);
  }
}
