<?php
// $Id: simplenews_access.module,v 1.1 2010/03/15 22:24:13 sutharsan Exp $

/**
 * @file simplenews_access.module
 * Provide access control for simplenews.
 *
 * @ingroup simplenews_access
 */

/**
 * Implements hook_menu().
 */
function simplenews_access_menu() {
  // TODO Move the admin page to People section?
  $items['admin/config/simplenews/access'] = array(
    'title' => 'Access control',
    'description' => 'Configure the access control to Simplenews newsletters.',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('simplenews_access_admin_by_role'),
    'access arguments' => array('administer simplenews settings'),
    'file' => 'simplenews_access.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_node_access_records().
 */
function simplenews_access_node_access_records($node) {
  // We only act upon Simplenews enabled content types.
  if (!simplenews_check_node_types(array($node->type))) {
    return;
  }

  // Return the grants matching the simplenews category.
  if (isset($node->simplenews['scid']) && $node->simplenews['scid']) {
    return reset(simplenews_access_get_grants($node->simplenews['scid']));
  }
}

/**
 * Get grants array by Simplenews category.
 *
 * @param $scids
 *   Simplenews category ID
 * @return Array of grants
 *   array[scid][rid] = array(
 *     'realm'         'simplenews_by_role',
 *     'gid'           Role ID
 *     'grant_view'    View permission
 *     'grant_update'  Update permission
 *     'grant_delete'  Delete permission
 *     'priority'      0
 *   )
 */
function simplenews_access_get_grants($scid = NULL) {
  $grants = &drupal_static(__FUNCTION__);

  if (!isset($grants) || ($scid && !isset($grants[$scid]))) {
    $query = db_select('simplenews_access', 'sa')
      ->fields('sa');
    if ($scid) {
      $query->condition('scid', $scid);
    }

    // Build array of grant permissions.
    foreach ($query->execute() as $data) {
      $grants[$data->scid][$data->rid] = array(
        'realm' => 'simplenews_by_role',
        'gid' => $data->rid,
        'grant_view'   => $data->grant_view,
        'grant_update' => $data->grant_update,
        'grant_delete' => $data->grant_delete,
        'priority' => 0,
      );
    }
  }

  return $scid ? array($scid => $grants[$scid]) : $grants;
}

/**
 * Implements hook_node_grants().
 */
function simplenews_access_node_grants($account, $op) {
  $grants['simplenews_by_role'] = array_keys($account->roles);
  return $grants;
}

/**
 * Implements hook_theme().
 */
function simplenews_access_theme() {
  return array(
    'simplenews_access_admin_by_role' => array(
      'render element' => 'form',
      'file' => 'simplenews_access.admin.inc',
    ),
  );
}
