<?php
/**
 * @file
 * Site-specific code for DefinitiveDrupal.org.
 */

/**
 * Implements hook_boot().
 *
 * Another approach would allow http://example.com/53/edit to work:
 * if (is_numeric(substr($_GET['q'], strpos($_GET['q'], '/')))) {
 *
 * @TODO replace with http://drupal.org/node/933888 when it lands.
 */
function dgd7_boot() {
  if (is_numeric($_GET['q'])) {
    $_GET['q'] = 'node/' . $_GET['q'];
  }
}

/**
 * Implements hook_remarkup_defaults().
 */
function dgd7_remarkup_defaults() {
  $rm = array();
  // Define the simple tips-style replacements, machine and human-readable.
  $tips = array(
    'tip' => t('Tip'),
    'note' => t('Note'),
    'hint' => t('Hint'),
    'reality' => t('Reality'),
    'caution' => t('Caution'),
    'gotcha' => t('Gotcha'),
    'new' => t('New in 7'),
  );
  foreach ($tips as $type => $name) {
    $rm['[/' . $type . ']'] = array(
      'before' => '<div class="dgd7-featured dgd7-' . $type . '"><strong class="dgd7-name">' . $name . '</strong>',
      'after' => '</div>',
    );
  }
  // A few rules are unique.
  $rm['[/file-txt]'] = array(
      'before' => '<code>',
      'after' => '</code>',
  );
  // NOTE!  This requires the codefilter module.
  $rm['[/file-php]'] = array(
      'before' => '<?php',
      'after' => '?>',
  );
  $rm['[/cli]'] = array(
    'before' => '<h4>Command-line steps</h4>
    <tt>',
    'after' => '</tt>',
  );
  return $rm;
}
