<?php
// $Id: simplenews_action.module,v 1.15 2010/03/15 22:26:48 sutharsan Exp $

/**
 * @file simplenews_action.module
 * Provide actions for simplenews.
 *
 * @ingroup simplenews
 * @todo Check and rework actions/trigger code for trigger API overhaul: http://drupal.org/node/224333#trigger_overhaul
 */

/*
* Implementation of hook_action_info()
*/
function simplenews_action_info() {
  return array(
    'simplenews_send_newsletter_action' => array(
      'description' => t('Send single simplenews newsletter'),
      'type' => 'simplenews',
      'configurable' => TRUE,
      'hooks' => array(
        'cron' => array('run'),
        'user' => array('insert'),
        'simplenews' => array('subscribe'),
      ),
    ),
    'simplenews_cron_action' => array(
      'description' => t('Send pending simplenews newsletters'),
      'type' => 'simplenews',
      'configurable' => FALSE,
      'hooks' => array(
        'cron' => array('run'),
      ),
    ),
    'simplenews_subscribe_user_action' => array(
      'type' => 'simplenews',
      'description' => t('Subscribe the user to a newsletter'),
      'configurable' => TRUE,
      'hooks' => array(
        'user' => array('insert', 'update'),
      ),
    ),
    'simplenews_unsubscribe_user_action' => array(
      'type' => 'simplenews',
      'description' => t('Unsubscribe the user from a newsletter'),
      'configurable' => TRUE,
      'hooks' => array(
        'user' => array('update', 'delete'),
      ),
    ),
  );
}

/**
* Implementation of hook_action_info_alter().
*
* Makes user and system actions available to the Simplenews 'subscribe' and 'unsubscribe' triggers.
*/
function simplenews_action_info_alter(&$actions) {
  foreach ($actions as $id => $action) {
    if ($action['type'] == 'user' || $action['type'] == 'system') {
      $actions[$id]['hooks']['simplenews'] = array('subscribe', 'unsubscribe');
    }
  }
}

/**
 * A configurable Drupal action. Send a simplenews newsletter.
 *   hook = cron: Send a newsletter to all subscribers.
 *   hook = user: Send a newsletter to the user who triggered the action.
 *
 *   Available context:
 *    $context['nid']     newsletter id
 *    $context['title']   newsletter title
 *    $context['resend']  allow resending of a previously send newsletter
 *
 *   @see simplenews_send_newsletter_action_form()
 *   @see simplenews_send_newsletter_action_submit()
 */
function simplenews_send_newsletter_action(&$object, $context = array()) {
  if ($context['hook'] == 'cron' || $context['hook'] == 'user' || $context['hook'] == 'simplenews') {

    // Determine newsletter receipients
    $accounts = array();
    if ($context['hook'] == 'user' || $context['hook'] == 'simplenews') {
      $accounts[] = $context['account'];
    }

    // Get sent status of this newsletter. The newsletter sent status is used not the sent status of individual emails.
    $newsletter = simplenews_newsletter_load($context['nid'], $context['vid']);

    // Send newsletter if resend is allowed OR newsletter is not yet send.
    if ($context['resend'] OR $newsletter->s_status == SIMPLENEWS_STATUS_SEND_NOT) {
      if ($context['hook'] == 'cron') {
        // Set newsletter sent status to pending if send by cron.
        $newsletter->s_status = SIMPLENEWS_STATUS_SEND_PENDING;
        simplenews_newsletter_save($newsletter);
      }
      simplenews_send_node($context['nid'], $accounts);
    }
    watchdog('action', 'Simplenews newsletter %title send.', array('%title' => $context['title']));
  }
}

/**
 * Implementation of a configurable Drupal action. Send newsletter
 */
function simplenews_send_newsletter_action_form($context) {
  //TODO improve usability by adding a pre-selection of newsletters before the newsletter issue selection
  //     Requires AHAH function to select newsletters issues based on selected newsletter
  //
  //  if (!isset($context['newsletter'])) {
  //    $context['newsletter'] = array();
  //  }
  if (!isset($context['newsletter_issue'])) {
    $context['newsletter_issue'] = array();
  }
  if (!isset($context['resend'])) {
    $context['resend'] = FALSE;
  }

  $categories = simplenews_category_list();
  //  $form['newsletter'] = array(
  //    '#title' => t('Newsletter'),
  //    '#type' => 'select',
  //    '#options' => $categories,
  //    '#default_value' => $context['newsletter'],
  //    '#description' => t('The newsletter series'),
  //  );
  $newsletters = simplenews_newsletter_load_multiple(array(), array('scid' => array_keys($categories)));
  $newsletter_nodes = array();
  foreach ($newsletters as $newsletter) {
    $newsletter_nodes[$newsletter->nid] = $newsletter->title;
  }
  $form['newsletter_issue'] = array(
    '#title' => t('Newsletter issue'),
    '#type' => 'select',
    '#options' => $newsletter_nodes,
    '#default_value' => $context['newsletter_issue'],
    '#description' => t('The newsletter issue to send'),
  );
  $form['resend'] = array(
    '#title' => t('Allow to resend newsletter'),
    '#type' => 'checkbox',
    '#default_value' => $context['resend'],
    '#description' => t('When checked a newsletter will be send even when already send before. The newsletter sent status is checked, not the status of individual email addresses. Use this for repeated (e.g. monthly) newsletters.'),
  );

  return $form;
}

/**
 * Validate simplenews_send_newsletter_action form submissions.
 */
function simplenews_send_newsletter_action_validate($form, $form_state) {
  $form_values = $form_state['values'];
  // Validate the send newsletter form.
  if (empty($form_values['newsletter_issue'])) {
    form_set_error('newsletter_issue', t('Please select a newsletter issue.'));
  }
}

/**
 * Process simplenews_send_newsletter_action form submissions.
 */
function simplenews_send_newsletter_action_submit($form, $form_state) {
  $form_values = $form_state['values'];

  $params = array(
    'nid' => $form_values['newsletter_issue'],
    'title' => $form['newsletter_issue']['#options'][$form_values['newsletter_issue']],
    'resend' => $form_values['resend'],
  );
  return $params;
}

/**
 * Implementation of a Drupal action. Send pending simplenews newsletters.
 */
function simplenews_cron_action(&$object, $context = array()) {
  simplenews_cron();
  watchdog('action', 'Simplenews cron executed.');
}

/**
 * A configurable Drupal action. Subscribe the user to a newsletter
 *   hook = user: Subscribe this user to selected newsletter
 *
 *   Available context:
 *    $context['slid']   Mailing list id
 *    $context['name']   List name
 *
 *   @see simplenews_subscribe_user_action_form()
 *   @see simplenews_subscribe_user_action_submit()
 */
function simplenews_subscribe_user_action(&$object, $context = array()) {
  if ($context['hook'] == 'user') {
    if (isset($context['slid'])) {
      // This action is only called in the context of user. User data is in $context.
      $account = $context['account'];
      simplenews_subscribe_user($account->mail, $context['slid'], FALSE, 'action');
      drupal_set_message(t('You have been subscribed to mailing list %list.', array('%list' => $context['name'])));
      watchdog('action', 'User %name subscribed to mailing list %list.', array('%name' => $account->name, '%list' => $context['name']));
    }
  }
}

/**
 * Implementation of a configurable Drupal action.
 */
function simplenews_subscribe_user_action_form($context) {
  if (!isset($context['list'])) {
    $context['list'] = array();
  }

  $lists = simplenews_get_mailing_lists(TRUE);
  $options = array();
  foreach ($tree as $newsletter) {
    $options[$list->slid] = $list->name;
  }
  $form['list'] = array(
    '#title' => t('Mailing list'),
    '#type' => 'select',
    '#options' => $options,
    '#description' => t('The mailing list the user will be subscribed to.'),
  );
  return $form;
}

/**
 * Process simplenews_subscribe_user_action form submissions.
 */
function simplenews_subscribe_user_action_submit($form, $form_state) {
  $form_values = $form_state['values'];

  $params = array(
    'slid' => $form_values['list'],
    'name' => $form['list']['#options'][$form_values['list']],
  );
  return $params;
}

/**
 * A configurable Drupal action. Unsubscribe the user from a newsletter
 *   hook = user: Unsubscribe this user from selected newsletter
 *
 *   Available context:
 *    $context['slid']    Mailing list id
 *    $context['name']    List name
 *
 *   @see simplenews_unsubscribe_user_action_form()
 *   @see simplenews_unsubscribe_user_action_submit()
 * @todo Replace time(): http://drupal.org/node/224333#time
 */
function simplenews_unsubscribe_user_action(&$object, $context = array()) {
  if ($context['hook'] == 'user') {
    if (isset($context['slid'])) {
      // This action is only called in the context of user. User data is in $context.
      $account = $context['account'];
      //TODO: Unsubscribing should be done by simplenews_unsubscribe_user but simplenews_get_user_subscription fails because the user is already removed
      $subscriber = reset(simplenews_subscriber_load_multiple(array(), array('mail' => $account->mail)));
      $data = array(
        'status' => SIMPLENEWS_SUBSCRIPTION_STATUS_UNSUBSCRIBED,
        'timestamp' => REQUEST_TIME,
        'source' => 'action',
      );
      simplenews_subscription_update(array('ssid' => $subscriber->ssid, 'slid' => $context['slid']), $data);
      drupal_set_message(t('You have been removed from the %newsletter subscription list.', array('%newsletter' => $context['name'])));
      watchdog('action', 'User %name unsubscribed from newsletter %newsletter.', array('%name' => $account->name, '%newsletter' => $context['name']));
    }
  }
}

/**
 * Implementation of a configurable Drupal action.
 */
function simplenews_unsubscribe_user_action_form($context) {
  if (!isset($context['list'])) {
    $context['list'] = array();
  }

  $lists = simplenews_get_mailing_lists(TRUE);
  $options = array();
  foreach ($tree as $newsletter) {
    $options[$list->slid] = $list->name;
  }
  $form['list'] = array(
    '#title' => t('Mailing list'),
    '#type' => 'select',
    '#options' => $options,
    '#description' => t('The mailing list the user will be unsubscribed from.'),
  );
  return $form;
}

/**
 * Process simplenews_unsubscribe_user_action form submissions.
 */
function simplenews_unsubscribe_user_action_submit($form, $form_state) {
  $form_values = $form_state['values'];

  $params = array(
    'slid' => $form_values['list'],
    'name' => $form['list']['#options'][$form_values['list']],
  );
  return $params;
}

/**
 * Implementation of hook_hook_info().
 */
function simplenews_hook_info() {
  return array(
    'simplenews' => array(
      'simplenews' => array(
        'subscribe' => array(
          'runs when' => t('After a user has been subscribed'),
        ),
        'unsubscribe' => array(
          'runs when' => t('After a user has been unsubscribed'),
        ),
      ),
    ),
  );
}
