<?php
// $Id$

/**
 * @file
 * This module provides an input filter which can be used in text formats to
 * allow users to use simple "[tip] Here's a tip! [/tip]"-style notation to
 * emphasize tips, notes, hints, and other paragraphs of text as specially
 * formatted, featured text.
 */

/**
 * Implements hook_filter_info().
 */
function remarkup_filter_info() {
  $filters['remarkup'] = array(
    'title' => t('Replacement markup'),
    'description' => t('Allows simple notation to indicate paragraphs of text to be wrapped in custom markup, for instance to emphasize tips, notes, or other featured interjections.'),
    'process callback' => '_remarkup_process',
    // Allow other modules to declare default tags and replacement markup.
    'default settings' => array(
      'rm' => module_invoke_all('remarkup_defaults'),
    ),
    'settings callback' => '_remarkup_settings',
    'tips callback' => '_remarkup_tips',
  );
  return $filters;
}

/**
 * Implements hook_theme().
 */
function remarkup_theme() {
  return array(
    'remarkup_settings' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Process callback for tag filter.
 */
function _remarkup_process($text, $filter) {
  if (!isset($filter->settings['rm']) || !is_array($filter->settings['rm'])) {
    return $text;
  }
  foreach ($filter->settings['rm'] as $ctag => $replace) {
    remarkup_replace_tags($text, $ctag, $replace['before'], $replace['after']);
  }
  return $text;
}

/**
 * Tips callback for tag filter.
 */
function _remarkup_tips($filter, $format, $long = FALSE) {
  $tips = '';
  if (!isset($filter->settings['rm']) || !is_array($filter->settings['rm'])) {
    if (user_access('administer filters')) {
      $tips .= '<p class="warning">' . t('No custom markup tag replacement defined.') . '</p>';
    }
  }
  elseif ($long) {
    $tips .= '<ul>';
    foreach ($filter->settings['rm'] as $tag => $replace) {
      $tips .= '<li>';
      $ctag = check_plain($tag);
      $otag = remarkup_otag($ctag);
      $tips .= '<code>' . $otag . '</code>';
      $tips .= ' ' . t('and') . ' ';
      $tips .= '<code>' . $ctag . '</code>';
      $tips .= ' ' . t('become') . ' ';
      $tips .= '<code>' . check_plain($replace['before']) . '</code>';
      $tips .= ' ' . t('and') . ' ';
      $tips .= '<code>' . check_plain($replace['after']) . '</code>.';
      $tips .= '</li>';
    }
    $tips .= '</ul>';
  }
  else {
    $tips .= t('Tags', array(), array('context' => 'Markup'));
    foreach ($filter->settings['rm'] as $tag => $replace) {
     $tips .= ' ' . check_plain(remarkup_otag($tag));
    }
    $tips .= t(' are replaced with before and after markup.');
  }
  if (user_access('administer filters')) {
    $tips .= ' ' . l(t('Configure format.'), 'admin/config/content/formats/' . $format->format);
  }
  return $tips;
}

/**
 * Settings callback for tag filter.
 */
function _remarkup_settings($form, $form_state, $filter, $format, $defaults) {
  // Declare the array that will hold our settings form elements.
  $settings = array();
  // Where filter settings are not defined, use the default settings.
  $filter->settings += $defaults;
  // Easy access to the values we need; "rm" is short for replacement markup.
  $rm = $filter->settings['rm'];

  $settings['rm'] = array(
    '#description' => t('To set tags and replacement markup, enter only the closing tag (such as &lt;/tip&gt;); the opening tag will be calculated automatically by removing the slash (&lt;tip&gt; in this example).  Then enter the before and after markup which will replace the opening and closing tag, respectively.'),
    '#theme' => 'remarkup_settings',
    '#element_validate' => array('remarkup_rm_form_keys_validate'),
    // Add CSS to make _remarkup_add_rm_formset() form elements look good.
    '#attached' => array(
      'css' => array(drupal_get_path('module', 'remarkup') . '/remarkup.css'),
    ),
  );
  $i = 0;
  foreach ($rm as $tag => $replace) {
    _remarkup_add_rm_formset($settings, $i, $tag, $replace);
    // Increment our number of filters by one.
    $i++;
  }
  // Always add two empty sets of form fields to be filled in.
  $total = $i+2;
  for ($i; $i < $total; $i++) {
    _remarkup_add_rm_formset($settings, $i);
  }
  return $settings;
}

/**
 * Add a set of form fields for adding a new tag and replacement markup pair.
 */
function _remarkup_add_rm_formset(&$settings, $i, $tag = '', $replace = array('before' => '', 'after' => '')) {
  $settings['rm'][$i] = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('remarkup-formset')),
  );
  $settings['rm'][$i]['tag'] = array(
    '#type' => 'textfield',
    '#title' => t('Tag'),
    '#maxlength' => 64,
    '#size' => 10,
    '#default_value' => $tag,
    '#element_validate' => array('remarkup_rm_form_tag_validate'),
  );
  $settings['rm'][$i]['before'] = array(
    '#type' => 'textfield',
    '#title' => t('Before'),
    '#maxlength' => 1024,
    '#size' => 45,
    '#default_value' => $replace['before'],
  );
  $settings['rm'][$i]['after'] = array(
    '#type' => 'textfield',
    '#title' => t('After'),
    '#maxlength' => 1024,
    '#size' => 45,
    '#default_value' => $replace['after'],
  );
}

/**
 * Validate each tag to include one and only one slash.
 */
function remarkup_rm_form_tag_validate($element, &$form_state, $whole_form) {
  if (strlen($element['#value']) && substr_count($element['#value'], '/') !== 1) {
    // We describe where the error is because after submission it is likely to
    // be in a non-visible vertical tab.
    form_error($element, t('In the Replacement markup Filter settings, each tag must be in the form of a closing tag with exactly one slash ("/").  The opening tag is calculated by removing the slash.'));
  }
}

/**
 * Rearrange form elements to be keyed by tag before filter_format_save() runs.
 */
function remarkup_rm_form_keys_validate($element, &$form_state) {
  $rm = array();
  // Create a tag-keyed version of each element.
  foreach ($element as $i => $value) {
    // Skip over non-value form elements (the ones we care about have numbers).
    if (!is_numeric($i))  continue;
    $key = $value['tag']['#value'];
    // Do not save empty keys.
    if (!$key) continue;
    $rm[$key] = array(
      'before' => $value['before']['#value'],
      'after' => $value['after']['#value'],
    );
  }

  form_set_value($element, $rm, $form_state);
}

/**
 * Replace with tags with markup given a closing tag (containing a /).
 *
 * @param $text
 *   String to be modified to use markup in place of tags, passed by reference.
 * @param $ctag
 *   A closing tag, identical to the opening tag except it includes a /.
 * @param $before
 *   Markup to replace the opening tag.
 * @param $after
 *   Markup to replace the closing tag.
 * @return NULL 
 */
function remarkup_replace_tags(&$text, $ctag, $before = '', $after = '') {
  $otag = preg_quote(remarkup_otag($ctag));
  $ctag = str_replace('/', '\/', preg_quote($ctag));
  $text = preg_replace(
    '/' . $otag . '(.+?)' . $ctag . '/s',
    "$before$1$after",
    $text
  );
}

/**
 * Take a closing tag and strip the slash to present the opening tag.
 */
function remarkup_otag($ctag) {
  return str_replace('/', '', $ctag);
}

/**
 * Theme callback to print description with settings form.
 */
function theme_remarkup_settings($vars) {
  $form = $vars['form'];
  return '<p>' . render($form['#description']) . '</p>'
         . drupal_render_children($form);
}
